name: All
on: push


jobs:
  build-test:
    strategy:
      matrix:
        os: [ macos-12 ]
#        os: [ macos-12, ubuntu-22.04 ]
#        os: [ macos-12, ubuntu-22.04, windows-2022]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.2

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race ./...

#
  build-artifacts-macos:
#    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-test
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser-pro
          version: 1.12.3
          args: release -f 1-darwin.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

      - name: who dist?
        run: ls -alF ./dist-darwin

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: dist-darwin
          path: ./dist-darwin


  #
  publish-artifacts:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-artifacts-macos]
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: dist-darwin
        path: dist-darwin

    - name: Install tree
      run: |
        sudo apt-get -y install tree

    - name: who dist?
      run: tree ./dist-darwin
#      run: ls -alF ./dist

#    - name: stat it
#      run: stat dist-darwin/sqlitr2_darwin_arm64/sqlitr2

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: who dist?
      run: tree ./dist-darwin

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.2

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        # either 'goreleaser' (default) or 'goreleaser-pro'
        distribution: goreleaser-pro
        version: 1.12.3
        args: release -f 2.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
        GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

    - name: who dist 2?
      run: tree ./dist-darwin
